#!/bin/bash
process
execute
server
hello this is my data
create one server
install one programming language
create one directory
download code
unzip code into directory
install dependencies
demon reload
restrat server
add user